/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista;

import controlador.Controlador_FRM_MantenimientoPrestamoLibros;
import javax.swing.JOptionPane;

/**
 *
 * @author Carlos
 */
public class FRM_MantenimientoPrestamoLibros extends javax.swing.JFrame {

    /**
     * Creates new form FRM_MantenimientoPrestamoLibros
     */
    
    Controlador_FRM_MantenimientoPrestamoLibros controlador_FRM_MantenimientoPrestamoLibros;
    
    public FRM_MantenimientoPrestamoLibros() {
        initComponents();
        this.setLocation(500,200);
        controlador_FRM_MantenimientoPrestamoLibros= new Controlador_FRM_MantenimientoPrestamoLibros(this);
        this.panel_Informacion1.agregarEventos(controlador_FRM_MantenimientoPrestamoLibros);
        this.panel_Botones1.agregarEventos(controlador_FRM_MantenimientoPrestamoLibros);
    }
    
    public void colocarNumeroPrestamo(String numeroPrestamo) {
        this.panel_Informacion1.colocarNumeroPrestamo(numeroPrestamo);
    }
    
    public void mostrarMensaje(String mensaje) {
        JOptionPane.showMessageDialog(null, mensaje);
    }
    
    public void mostrarInformacion(String arreglo[]) {
        this.panel_Informacion1.mostrarInformacion(arreglo);
    }
    
    public String[] devolverInformacion() {
        return this.panel_Informacion1.devolverInformacion();
    }
    
    public void resetearGUI() {
        this.panel_Informacion1.limpiarCampos();
        this.panel_Botones1.habilitarBuscar();
        this.panel_Botones1.deshabilitarAgregar();
        this.panel_Botones1.deshabilitarEdicion();
    }
    
    public String devolverNumeroPrestamo() {
        return this.panel_Informacion1.devolverNumeroPrestamo();
    }
    
    public void habilitarAgregar() {
        this.panel_Informacion1.deshabilitarCampoNumeroPrestamo();
        this.panel_Informacion1.habilitarCampos();
        this.panel_Botones1.habilitarAgregar();
        this.panel_Botones1.deshabilitarBuscar();
    }
    
    public void habilitarEdicion() {
        this.panel_Informacion1.deshabilitarCampoNumeroPrestamo();
        this.panel_Informacion1.habilitarCampos();
        this.panel_Botones1.deshabilitarBuscar();
        this.panel_Botones1.habilitarEdicion();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel_Informacion1 = new vista.Panel_Informacion();
        panel_Botones1 = new vista.Panel_Botones();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(panel_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(panel_Informacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panel_Informacion1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(panel_Botones1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRM_MantenimientoPrestamoLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRM_MantenimientoPrestamoLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRM_MantenimientoPrestamoLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRM_MantenimientoPrestamoLibros.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRM_MantenimientoPrestamoLibros().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private vista.Panel_Botones panel_Botones1;
    private vista.Panel_Informacion panel_Informacion1;
    // End of variables declaration//GEN-END:variables
}
